sudo: required
dist: trusty
group: edge

language: node_js

os:
  - linux

node_js:
  - '6'
  - '7'
  - '8'

before_install:
  - npm install -g npm
  - npm --version

after_success:
  - npm run coveralls
  - npm run coverage-clean

before_deploy:
  - echo "Deploying to GitHub releases"
  - ls -al releases

deploy:
  provider: releases
  api_key:
    secure: "m2jenywh8NbE3zhA+pTPhY5lL6ckqQDkE1KzTy8Tjmhihqv9QOsn78mO7CUCd1oL6q5GwQp6TSV0PEl53i081u2mb2kHAYCMVprtLJVDHy84aDmzrT8NlpPtKbfvCIhh6KzxmIsLSJl5CO6Irtavl51Mq1IMRvKsYAs4qB1SVYc797ECDWGRFmB8r5JFqyo2UwOLqQtgmwcHIlMaiDH4sHT9myWBW55h4GfvDxrAKAKMRoMZTqgvfuZe2WiJoniWiSzfhXDLY1kix/fywQh5Obi6TAkMIVLZ1K4wNKGfxbbJnAQyVTsX+DFLVUzdWbfR4W94d6Db+GiczojW5xN5iaTajzlJFhQsljfdq8C7ywMU3VD/ktgdjgWVngV2S8zcy2ms5KmuRCLPQ3cDqCLPf+Se/NjWNf7Uyok+NbV9O8WH/CGz8QNG/tvgmvK4mYUCxGZvIdXXon7ru6fT0IKhpIovXI6m0IuvkCB0L3sIYzZ7/xL06Shr91wFmYo2pMGuxoVtKYOm8/sBN+QwggNh3rTqAGN2XrpBd6BlnnwPwZhAoDz/27YW61xCzNkXEe3hD/c0/hVgV/h5G1ltQqROz5mAtxVKKYngVFzQ6W0eUMGqyNe7PCGMyGFe1239YxO6/na/Bs8DT9UUlLANy1IrGhU6QW6gyC7Kn5CL0Orp2S4="
  file_glob: true
  file:
    - 'releases/*.*'
  overwrite: true
  skip_cleanup: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    tags: true  # Deploy app only when a tag is applied to the commit
    node: '4'
